http:
  host: "localhost"
  port: 3000

db:
  mysql:
    type: "mysql"
    autoLoadEntities: true # 自动加载实体
    host: "localhost"
    port: 3306
    username: "root"
    password: "lynn0922.."
    database: "management"
    synchronize: true # 是否自动同步实体文件,生产环境建议关闭
